language: node_js
node_js:
- 10

sudo: false
script: yarn test
before_script:
- yarn prettier:check
deploy:
  - provider: npm
    email: 'julien.ducro@deskpro.com'
    api_key: '${NPM_TOKEN}'
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script:
      - yarn deploy-storybook
    on:
      branch: master
