language: node_js
node_js:
- 10
sudo: false
script: yarn test
before_script:
- yarn prettier:check
branches:
  only:
  - master
deploy:
  - provider: npm
    email: 'julien.ducro@deskpro.com'
    api_key: '${NPM_TOKEN}'
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script:
      - lerna run --scope @deskpro/content-editor-storybook deploy-storybook -- -- --ci
    on:
      branch: master
