language: node_js
node_js:
- 10
sudo: false
script: yarn test
before_script:
- yarn prettier:check
branches:
  only:
  - master
deploy:
  provider: npm
  api_key: '${NPM_TOKEN}'
  skip_cleanup: true
  on:
    tags: true
